### ISSUE TITLE
Is there a way to have shared variables?

### ISSUE THREAD

**Issue by seifsallam** [outaTiME/grunt-config#1]

**Comment by outaTiME** [comment]
Any news about the PR, here my solution in another project:

https://github.com/outaTiME/grunt-replace/issues/75

cheers

**Comment by outaTiME** [comment]
No updates, closing for now ...

**Comment by almeidap** [comment]
If you wish to use the new features from my pull request before it gets merged, you can use this tag: https://github.com/almeidap/grunt-config/releases/tag/0.5.0-pre
